version: '3.8'
services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: 'Test_123'
    ports:
      - '1433:1433'
  api:
    build: ./backend
    ports:
      - '8080:8080'
      - '8081:8081'
    depends_on:
      - db
  # frontend:
  #   build: ./frontend/web
  #   depends_on:
  #     - api
  # microservice:
  #   build: ./microservice
  #   depends_on:
  #     - api
