services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: 'Test_123'
    ports:
      - '1433:1433'
    volumes:
      - type: volume
        source: mssql-data
        target: /var/opt/mssql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-U", "sa", "-P", "Test_123", "-Q", "SELECT 1"]
      interval: 11s
      timeout: 5s
      retries: 7
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - '5672:5672' # Default RabbitMQ port
      - '15672:15672' # Management plugin UI
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 6s
      retries: 6
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
  listener:
    build:
      context: ./Listener
      dockerfile: Dockerfile.Listener
    ports:
      - '8082:8082'
      - '8083:8083'
    depends_on:
      rabbitmq:
        condition: service_healthy
    # volumes:
    #   - listener-data:/path/to/listener/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8082/api/HealthCheck || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
  api:
    build:
      context: ./API
      dockerfile: Dockerfile.API
    ports:
      - '8080:8080'
      - '8081:8081'
    depends_on:
      listener:
        condition: service_healthy
      mssql:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/api/HealthCheck || exit 1"]
      interval: 14s
      timeout: 5s
      retries: 6

networks:
  app-network:

volumes:
  mssql-data:
  redis-data:
  listener-data: